apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tx-smtp-relay.fullname" . }}
  labels:
    {{- include "tx-smtp-relay.labels" . | nindent 4 }}
data:
  smtp-relay-host: {{ .Values.smtp.host | quote }}
  smtp-relay-myhostname: {{ .Values.smtp.myhostname | default (include "tx-smtp-relay.fullname" .) | quote }}
  smtp-relay-username: {{ .Values.smtp.username | quote }}
