apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tx-smtp-relay.fullname" . }}
  labels:
    {{- include "tx-smtp-relay.labels" . | nindent 4 }}
data:
  smtp-relay-password: {{ .Values.smtp.password | b64enc }}
